### ISSUE TITLE
progressData calculate

### ISSUE THREAD

**Issue by renyijiu** [fairytale110/DailyImageWidget#1]
https://github.com/fairytale110/DailyImageWidget/blob/160d004bc25c56de3dc7dec5b3bc04e854fab193/app/src/main/java/tech/nicesky/dailyimage/widget/DailyImageService.java#L136

闰年366天，计算结果可能不影响，但可以考虑优化下（不太懂java，看的时候发现的）

**Comment by fairytale110** [comment]
可以可以

**Comment by fairytale110** [comment]
This has been fixed，Thank you very much for your feedback.
